version: '3.8'

services:
  audio-transcription:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    container_name: audio-transcription-gpu
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./audios:/app/audios
      - ./textos:/app/textos
      - ./logs:/app/logs
      - ./.env:/app/.env
    deploy:
      resources:
        limits:
          memory: 24G
          cpus: '14.0'
        reservations:
          memory: 12G
          cpus: '4.0'
    shm_size: 4gb
    command: python main.py --start-date 2024-01-01 --end-date 2024-01-31
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
