services:
  # Servicio principal de procesamiento de audio
  audio-to-text:
    build: .
    container_name: audio-to-text-processor
    volumes:
      # Montar directorios para persistir datos
      - ./audios:/app/audios
      - ./textos:/app/textos
      - ./logs:/app/logs
      # Montar archivo de configuración si existe
      - ./.env:/app/.env:ro
    environment:
      # Variables de entorno para MySQL
      - MYSQL_HOST=${MYSQL_HOST:-localhost}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-llamadas}
      
      # Variables para URLs de audio
      - AUDIO_BASE_URL=${AUDIO_BASE_URL:-}
      
      # Configuración de Whisper
      - WHISPER_MODEL=${WHISPER_MODEL:-large}
      
      # Configuración de procesamiento paralelo
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-3}
      - MAX_CONCURRENT_TRANSCRIPTIONS=${MAX_CONCURRENT_TRANSCRIPTIONS:-2}
      
      # Configuración optimizada para CPU
      - CPU_OPTIMIZED=${CPU_OPTIMIZED:-true}
      - MAX_CPU_WORKERS=${MAX_CPU_WORKERS:-4}
      - ENABLE_PARALLEL_DOWNLOADS=${ENABLE_PARALLEL_DOWNLOADS:-true}
      - ENABLE_PARALLEL_TRANSCRIPTIONS=${ENABLE_PARALLEL_TRANSCRIPTIONS:-true}
      
      # Configuración optimizada para GPU
      - GPU_OPTIMIZED=${GPU_OPTIMIZED:-false}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      
      # Configuración de memoria
      - MAX_MEMORY_USAGE=${MAX_MEMORY_USAGE:-8G}
      - CHUNK_SIZE=${CHUNK_SIZE:-5}
      
      # Configuración de limpieza automática
      - AUTO_CLEANUP=${AUTO_CLEANUP:-true}
      - CLEANUP_AUDIO_FILES=${CLEANUP_AUDIO_FILES:-true}
      - CLEANUP_TEMP_FILES=${CLEANUP_TEMP_FILES:-true}
      - KEEP_TRANSCRIPTS=${KEEP_TRANSCRIPTS:-true}
      - CLEANUP_DELAY=${CLEANUP_DELAY:-0}
      
      # Configuración de modelo persistente
      - PERSISTENT_MODEL=${PERSISTENT_MODEL:-true}
      - MODEL_CACHE_ENABLED=${MODEL_CACHE_ENABLED:-true}
      
      # Configuración de GPU
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    
    # Comando por defecto (se puede sobrescribir)
    command: python main.py --start-date 2024-01-01 --end-date 2024-01-31
    
    # Configuración de red
    networks:
      - audio-network
    
    # Configuración de recursos (CPU por defecto)
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    
    # Configuración de memoria compartida
    shm_size: 2gb

  # Servicio de cache persistente del modelo Whisper (opcional)
  whisper-cache:
    build: .
    container_name: whisper-model-cache
    command: python whisper_service.py
    volumes:
      - ./audios:/app/audios
      - ./textos:/app/textos
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
      - /tmp/whisper_cache:/root/.cache/whisper  # Persistir cache del modelo
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL:-tiny}
      # Variables de entorno para MySQL (si el servicio necesita acceso directo)
      - MYSQL_HOST=${MYSQL_HOST:-localhost}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-llamadas}
    networks:
      - audio-network
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '4.0'  # Asignar CPUs para el servicio del modelo
        reservations:
          memory: 8G
          cpus: '2.0'
    profiles:
      - cache  # Solo se ejecuta cuando se usa el perfil 'cache'

  # Servicio optimizado para GPU (opcional)
  audio-to-text-gpu:
    build: 
      context: .
      dockerfile: Dockerfile.gpu
    container_name: audio-to-text-processor-gpu
    volumes:
      - ./audios:/app/audios
      - ./textos:/app/textos
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      # Variables de entorno para MySQL
      - MYSQL_HOST=${MYSQL_HOST:-localhost}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-llamadas}
      
      # Variables para URLs de audio
      - AUDIO_BASE_URL=${AUDIO_BASE_URL:-}
      
      # Configuración de Whisper optimizada para GPU
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      
      # Configuración optimizada para GPU
      - GPU_OPTIMIZED=${GPU_OPTIMIZED:-true}
      - CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-0}
      
      # Configuración de procesamiento paralelo para GPU
      - MAX_CONCURRENT_DOWNLOADS=${MAX_CONCURRENT_DOWNLOADS:-5}
      - MAX_CONCURRENT_TRANSCRIPTIONS=${MAX_CONCURRENT_TRANSCRIPTIONS:-3}
      
      # Configuración de limpieza automática
      - AUTO_CLEANUP=${AUTO_CLEANUP:-true}
      - CLEANUP_AUDIO_FILES=${CLEANUP_AUDIO_FILES:-true}
      - CLEANUP_TEMP_FILES=${CLEANUP_TEMP_FILES:-true}
      - KEEP_TRANSCRIPTS=${KEEP_TRANSCRIPTS:-true}
      - CLEANUP_DELAY=${CLEANUP_DELAY:-0}
    
    # Comando por defecto
    command: python main.py --start-date 2024-01-01 --end-date 2024-01-31
    
    # Configuración de red
    networks:
      - audio-network
    
    # Configuración de recursos para GPU
    deploy:
      resources:
        limits:
          memory: 16G
          cpus: '6.0'
        reservations:
          memory: 8G
          cpus: '2.0'
    
    # Configuración de memoria compartida para GPU
    shm_size: 4gb
    
    # Configuración de GPU
    runtime: nvidia
    
    profiles:
      - gpu  # Solo se ejecuta cuando se usa el perfil 'gpu'

networks:
  audio-network:
    driver: bridge